### ISSUE TITLE
Prawn+ really dependent on ruby 2.7?

### ISSUE THREAD

**Issue by gr8bit** [bkuhlmann/prawn_plus#2]
Prawn+ 10.0.0 has a dependency on Ruby 2.7 so I can't use it in my 2.6 projects. Why? Does it use any ruby 2.7 only features? Is it even incompatible to 2.3? Any hint greatly appreciated, I'd like to use P+ :)

P.S.: [Rails 6 requires Ruby 2.5.](https://github.com/rails/rails/pull/34754)

**Comment by bkuhlmann** [comment]
Hey @gr8bit :wave:

Technically, 10.0.0 doesn't have any hard restrictions on Ruby 2.7.0. As for Ruby 2.3.0, I'm not sure as I only build against the latest Ruby versions.

You could probably fallback (pin) to [9.1.4](https://github.com/bkuhlmann/prawn_plus/releases/tag/9.1.4) until you are ready to use Ruby 2.7.0 as that was the last version to support Ruby 2.6.5.

The main reason for supporting Ruby 2.7.0 is because maintaining [~30 projects](https://www.alchemists.io/projects) for free is a decent amount of work so can't support multiple versions of Ruby. 😅

**Comment by gr8bit** [comment]
Thank you for the fast reply @bkuhlmann ! 😃

I tried, but I can't fallback to 9.1.4 as that one *requires* Rails 5 - I'm on Rails 6. 😆 I totally understand your maintenance efforts though and will stick to the good old [prawnto_2](https://github.com/getjobber/prawnto) for now - may it live long. 🤞

Best, Niklas
